language: node_js
node_js:
- '6.9'
branches:
  only:
  - master

before_script:
- npm install -g @angular/cli
script:
- ng build --prod
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: eviction-maps
  acl: public_read
  local_dir: dist
  on:
    branch: master
    repo: EvictionLab/eviction-maps
